server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huodan?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: shen20010402
    initialization-mode: never
    sql-script-encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      location: ${java.io.tmpdir}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.huodan.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl